In [1]:
import numpy as np

In [48]:
n=5
p=np.ones((1,n))*(1/n)

phit=0.6
pmis=0.2


In [42]:
p

array([[ 0.2,  0.2,  0.2,  0.2,  0.2]])

In [20]:
world=['g','r','r','g','g']

In [49]:
sens=['r']
def normalise(mat):
    mat/=np.sum(mat)
    return mat

def sense_step(p,Z):
    for i,color in enumerate(world):
        if color==Z:
            p[0][i]*=phit

        else:
            p[0][i]*=pmis
    return normalise(p)

def sense(p,Z):
    for z in Z:
        p=sense_step(p,z)
    return p



In [50]:
p=sense(p,sens)

In [51]:
p

array([[ 0.11111111,  0.33333333,  0.33333333,  0.11111111,  0.11111111]])

In [67]:
def move(p,U):
    p=np.roll(p,U)
    return p

In [70]:
p

array([[ 0.11111111,  0.33333333,  0.33333333,  0.11111111,  0.11111111]])

In [71]:
np.roll(p,1)


array([[ 0.11111111,  0.11111111,  0.33333333,  0.33333333,  0.11111111]])